# ==========================================
# 记账系统接口自动化测试环境配置
# ==========================================

# 当前测试环境
environment: test


# ==========================================
# 接口基础地址
# ==========================================
#
# Django 本地开发环境：
#
# python manage.py runserver
#
# 默认地址：
# http://127.0.0.1:8000
#
# ==========================================

base_url: "http://127.0.0.1:8000"


# ==========================================
# 接口统一前缀
# ==========================================

api_prefix: "/api/v1"


# ==========================================
# 请求配置
# ==========================================

request:
  # 单个接口最大等待时间，单位：秒
  timeout: 10


# ==========================================
# 测试账号
# ==========================================
#
# 自动化阶段先使用已经存在的测试账号。
#
# 后面可以进一步优化为：
#
# 1. 自动注册测试账号；
# 2. 自动生成测试数据；
# 3. 测试结束自动清理数据。
#
# 注意：
# 不要把真实密码提交到 Git。
# 当前开发阶段可以先使用专门的测试账号。
#
# ==========================================

test_user:
  username: "test001"
  password: "Test@123456"